In [1]:
L=[1,2,3,4]

In [2]:
import sys

In [3]:
sys.getsizeof(L)

88

In [4]:
import numpy as np

In [5]:
o=np.array([1,2,3,4])

In [6]:
o

array([1, 2, 3, 4])

In [7]:
o.nbytes

16

In [8]:
c=[[1,2,3,4],[5,7,9]]
sys.getsizeof(c)

72

In [9]:
x=np.array([[1,2,3,4],[5,7,9]])

C:\Users\mahen\AppData\Local\Temp\ipykernel_28084\1180105464.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x=np.array([[1,2,3,4],[5,7,9]])


In [10]:
x

array([list([1, 2, 3, 4]), list([5, 7, 9])], dtype=object)

In [11]:
x.nbytes

16

In [12]:
np.zeros([7,7])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [13]:
i=np.full([5,3],5)

In [14]:
i

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [15]:
i.reshape(3,5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [16]:
i.reshape(1,15)

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [17]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
p=np.arange(10,200)

In [19]:
p.nbytes

760

In [20]:
p

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
       179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 19

In [21]:
r=[]
for i in range(10,200):
    r.append(i)

In [22]:
r

[10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191

In [23]:
sys.getsizeof(r)

1656

In [24]:
# in sql 1000000 rows --------> 3 to 5 min
# but pandas will take just 10 to 15 sec

In [25]:
import pandas as pd
import numpy as np

In [26]:
a=[1,2,3,4,5]
b=pd.Series(a)

In [27]:
b

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [28]:
#products = [[item1],[],[],[],[],[]]

In [29]:
employees=[[1,'mahendra',3,60000,30],[2,'mahi',4,50000,40],[5,'mahima',2,40000,28],[3,'manohar',1,30000,43]]

In [30]:
employees

[[1, 'mahendra', 3, 60000, 30],
 [2, 'mahi', 4, 50000, 40],
 [5, 'mahima', 2, 40000, 28],
 [3, 'manohar', 1, 30000, 43]]

In [31]:
pd.DataFrame(employees, columns =['id','name','mgr_id','salary','age'])

id      name  mgr_id  salary  age
0   1  mahendra       3   60000   30
1   2      mahi       4   50000   40
2   5    mahima       2   40000   28
3   3   manohar       1   30000   43

In [32]:
employees={'id':[1,2,5,3, np.nan],
           'name':['mahendra','mahi','maha','sam', 'aodihf'],
           'mgr_id':[2,3,np.nan,5, 8],
           'salary':[40000,30000,20000,50000,np.nan],
           'age':[30,40,20,45,np.nan]}

In [33]:
np.arange(10,200,20, dtype = float)

array([ 10.,  30.,  50.,  70.,  90., 110., 130., 150., 170., 190.])

In [34]:
employees

{'id': [1, 2, 5, 3, nan],
 'name': ['mahendra', 'mahi', 'maha', 'sam', 'aodihf'],
 'mgr_id': [2, 3, nan, 5, 8],
 'salary': [40000, 30000, 20000, 50000, nan],
 'age': [30, 40, 20, 45, nan]}

In [35]:
df=pd.DataFrame(employees)

In [36]:
df

id      name  mgr_id   salary   age
0  1.0  mahendra     2.0  40000.0  30.0
1  2.0      mahi     3.0  30000.0  40.0
2  5.0      maha     NaN  20000.0  20.0
3  3.0       sam     5.0  50000.0  45.0
4  NaN    aodihf     8.0      NaN   NaN

In [37]:
df.head(3)

id      name  mgr_id   salary   age
0  1.0  mahendra     2.0  40000.0  30.0
1  2.0      mahi     3.0  30000.0  40.0
2  5.0      maha     NaN  20000.0  20.0

In [38]:
df.tail()

id      name  mgr_id   salary   age
0  1.0  mahendra     2.0  40000.0  30.0
1  2.0      mahi     3.0  30000.0  40.0
2  5.0      maha     NaN  20000.0  20.0
3  3.0       sam     5.0  50000.0  45.0
4  NaN    aodihf     8.0      NaN   NaN

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   id      4 non-null      float64
 1   name    5 non-null      object 
 2   mgr_id  4 non-null      float64
 3   salary  4 non-null      float64
 4   age     4 non-null      float64
dtypes: float64(4), object(1)
memory usage: 328.0+ bytes


In [40]:
df.describe()

id    mgr_id        salary        age
count  4.000000  4.000000      4.000000   4.000000
mean   2.750000  4.500000  35000.000000  33.750000
std    1.707825  2.645751  12909.944487  11.086779
min    1.000000  2.000000  20000.000000  20.000000
25%    1.750000  2.750000  27500.000000  27.500000
50%    2.500000  4.000000  35000.000000  35.000000
75%    3.500000  5.750000  42500.000000  41.250000
max    5.000000  8.000000  50000.000000  45.000000

In [41]:
df['id']

0    1.0
1    2.0
2    5.0
3    3.0
4    NaN
Name: id, dtype: float64

In [42]:
df[['id','name','salary']] 

id      name   salary
0  1.0  mahendra  40000.0
1  2.0      mahi  30000.0
2  5.0      maha  20000.0
3  3.0       sam  50000.0
4  NaN    aodihf      NaN

In [43]:
df.iloc[1:4]

id  name  mgr_id   salary   age
1  2.0  mahi     3.0  30000.0  40.0
2  5.0  maha     NaN  20000.0  20.0
3  3.0   sam     5.0  50000.0  45.0

In [44]:
for i in range(1,10):
    print(i,end='')

123456789

In [45]:
df

id      name  mgr_id   salary   age
0  1.0  mahendra     2.0  40000.0  30.0
1  2.0      mahi     3.0  30000.0  40.0
2  5.0      maha     NaN  20000.0  20.0
3  3.0       sam     5.0  50000.0  45.0
4  NaN    aodihf     8.0      NaN   NaN

In [46]:
df[df['salary']>30000]

id      name  mgr_id   salary   age
0  1.0  mahendra     2.0  40000.0  30.0
3  3.0       sam     5.0  50000.0  45.0

In [47]:
df[(df['age']>20) & (df['salary']>40000)]

id name  mgr_id   salary   age
3  3.0  sam     5.0  50000.0  45.0

In [48]:
df[(df['age']>30) | (df['salary']>40000)]

id  name  mgr_id   salary   age
1  2.0  mahi     3.0  30000.0  40.0
3  3.0   sam     5.0  50000.0  45.0

In [49]:
employees2={'id':[1,2,5,3, None],
           'name':['mahendra','mahi','maha','sam', 'aodihf'],
           'mgr_id':[2,3,None,5, 8],
           'salary':[40000,30000,20000,50000,None],
           'age':[30,40,20,45,None]}

In [50]:
employees2=pd.DataFrame(employees2)

In [51]:
employees2

id      name  mgr_id   salary   age
0  1.0  mahendra     2.0  40000.0  30.0
1  2.0      mahi     3.0  30000.0  40.0
2  5.0      maha     NaN  20000.0  20.0
3  3.0       sam     5.0  50000.0  45.0
4  NaN    aodihf     8.0      NaN   NaN

In [52]:
df

id      name  mgr_id   salary   age
0  1.0  mahendra     2.0  40000.0  30.0
1  2.0      mahi     3.0  30000.0  40.0
2  5.0      maha     NaN  20000.0  20.0
3  3.0       sam     5.0  50000.0  45.0
4  NaN    aodihf     8.0      NaN   NaN

In [53]:
df['updated_salary']= df['salary']*1.1

In [54]:
df

id      name  mgr_id   salary   age  updated_salary
0  1.0  mahendra     2.0  40000.0  30.0         44000.0
1  2.0      mahi     3.0  30000.0  40.0         33000.0
2  5.0      maha     NaN  20000.0  20.0         22000.0
3  3.0       sam     5.0  50000.0  45.0         55000.0
4  NaN    aodihf     8.0      NaN   NaN             NaN

In [55]:
u=df.drop('age', axis=1)

In [56]:
u

id      name  mgr_id   salary  updated_salary
0  1.0  mahendra     2.0  40000.0         44000.0
1  2.0      mahi     3.0  30000.0         33000.0
2  5.0      maha     NaN  20000.0         22000.0
3  3.0       sam     5.0  50000.0         55000.0
4  NaN    aodihf     8.0      NaN             NaN

In [57]:
df

id      name  mgr_id   salary   age  updated_salary
0  1.0  mahendra     2.0  40000.0  30.0         44000.0
1  2.0      mahi     3.0  30000.0  40.0         33000.0
2  5.0      maha     NaN  20000.0  20.0         22000.0
3  3.0       sam     5.0  50000.0  45.0         55000.0
4  NaN    aodihf     8.0      NaN   NaN             NaN

In [58]:
df.drop('updated_salary', axis=1, inplace = True)

In [59]:
df

id      name  mgr_id   salary   age
0  1.0  mahendra     2.0  40000.0  30.0
1  2.0      mahi     3.0  30000.0  40.0
2  5.0      maha     NaN  20000.0  20.0
3  3.0       sam     5.0  50000.0  45.0
4  NaN    aodihf     8.0      NaN   NaN

In [60]:
df['age']

0    30.0
1    40.0
2    20.0
3    45.0
4     NaN
Name: age, dtype: float64

In [61]:
df['id']*2

0     2.0
1     4.0
2    10.0
3     6.0
4     NaN
Name: id, dtype: float64

In [62]:
df

id      name  mgr_id   salary   age
0  1.0  mahendra     2.0  40000.0  30.0
1  2.0      mahi     3.0  30000.0  40.0
2  5.0      maha     NaN  20000.0  20.0
3  3.0       sam     5.0  50000.0  45.0
4  NaN    aodihf     8.0      NaN   NaN

In [63]:
df['id']=df['id']*2

In [64]:
df

id      name  mgr_id   salary   age
0   2.0  mahendra     2.0  40000.0  30.0
1   4.0      mahi     3.0  30000.0  40.0
2  10.0      maha     NaN  20000.0  20.0
3   6.0       sam     5.0  50000.0  45.0
4   NaN    aodihf     8.0      NaN   NaN

In [65]:
df

id      name  mgr_id   salary   age
0   2.0  mahendra     2.0  40000.0  30.0
1   4.0      mahi     3.0  30000.0  40.0
2  10.0      maha     NaN  20000.0  20.0
3   6.0       sam     5.0  50000.0  45.0
4   NaN    aodihf     8.0      NaN   NaN

In [66]:
df.isnull()

id   name  mgr_id  salary    age
0  False  False   False   False  False
1  False  False   False   False  False
2  False  False    True   False  False
3  False  False   False   False  False
4   True  False   False    True   True

In [67]:
df.isnull().sum()

id        1
name      0
mgr_id    1
salary    1
age       1
dtype: int64

In [68]:
df.dropna(inplace=True)

In [69]:
df

id      name  mgr_id   salary   age
0  2.0  mahendra     2.0  40000.0  30.0
1  4.0      mahi     3.0  30000.0  40.0
3  6.0       sam     5.0  50000.0  45.0

In [70]:
employees2

id      name  mgr_id   salary   age
0  1.0  mahendra     2.0  40000.0  30.0
1  2.0      mahi     3.0  30000.0  40.0
2  5.0      maha     NaN  20000.0  20.0
3  3.0       sam     5.0  50000.0  45.0
4  NaN    aodihf     8.0      NaN   NaN

In [71]:
employees2.fillna(employees2['salary'].sum())

id      name    mgr_id    salary       age
0       1.0  mahendra       2.0   40000.0      30.0
1       2.0      mahi       3.0   30000.0      40.0
2       5.0      maha  140000.0   20000.0      20.0
3       3.0       sam       5.0   50000.0      45.0
4  140000.0    aodihf       8.0  140000.0  140000.0

In [72]:
employees2['salary']=employees2['salary'].fillna(employees2['salary'].sum())

In [73]:
employees2

id      name  mgr_id    salary   age
0  1.0  mahendra     2.0   40000.0  30.0
1  2.0      mahi     3.0   30000.0  40.0
2  5.0      maha     NaN   20000.0  20.0
3  3.0       sam     5.0   50000.0  45.0
4  NaN    aodihf     8.0  140000.0   NaN

In [74]:
employees2['age']=employees2['age'].fillna(employees2['age'].sum())

In [75]:
employees2

id      name  mgr_id    salary    age
0  1.0  mahendra     2.0   40000.0   30.0
1  2.0      mahi     3.0   30000.0   40.0
2  5.0      maha     NaN   20000.0   20.0
3  3.0       sam     5.0   50000.0   45.0
4  NaN    aodihf     8.0  140000.0  135.0

In [76]:
employees2

id      name  mgr_id    salary    age
0  1.0  mahendra     2.0   40000.0   30.0
1  2.0      mahi     3.0   30000.0   40.0
2  5.0      maha     NaN   20000.0   20.0
3  3.0       sam     5.0   50000.0   45.0
4  NaN    aodihf     8.0  140000.0  135.0

In [77]:
employees3={'id':[1,2,5,3, None],
           'name':['mahendra','mahi','maha','sam', 'aodihf'],
           'mgr_id':[2,3,None,5, 8],
           'salary':[40000,30000,20000,50000,None],
           'age':[30,40,20,45,None]}

In [78]:
employees3 = pd.DataFrame(employees3)

In [79]:
employees3

id      name  mgr_id   salary   age
0  1.0  mahendra     2.0  40000.0  30.0
1  2.0      mahi     3.0  30000.0  40.0
2  5.0      maha     NaN  20000.0  20.0
3  3.0       sam     5.0  50000.0  45.0
4  NaN    aodihf     8.0      NaN   NaN

In [80]:
employees3['age']=employees3['age']*2

In [81]:
employees3

id      name  mgr_id   salary   age
0  1.0  mahendra     2.0  40000.0  60.0
1  2.0      mahi     3.0  30000.0  80.0
2  5.0      maha     NaN  20000.0  40.0
3  3.0       sam     5.0  50000.0  90.0
4  NaN    aodihf     8.0      NaN   NaN

In [82]:
employees3['age']=employees3['age'].apply(lambda x: x*2)

In [83]:
employees3

id      name  mgr_id   salary    age
0  1.0  mahendra     2.0  40000.0  120.0
1  2.0      mahi     3.0  30000.0  160.0
2  5.0      maha     NaN  20000.0   80.0
3  3.0       sam     5.0  50000.0  180.0
4  NaN    aodihf     8.0      NaN    NaN

In [84]:
employees3

id      name  mgr_id   salary    age
0  1.0  mahendra     2.0  40000.0  120.0
1  2.0      mahi     3.0  30000.0  160.0
2  5.0      maha     NaN  20000.0   80.0
3  3.0       sam     5.0  50000.0  180.0
4  NaN    aodihf     8.0      NaN    NaN

In [85]:
employees4=pd.DataFrame(employees3)

In [86]:
employees4

id      name  mgr_id   salary    age
0  1.0  mahendra     2.0  40000.0  120.0
1  2.0      mahi     3.0  30000.0  160.0
2  5.0      maha     NaN  20000.0   80.0
3  3.0       sam     5.0  50000.0  180.0
4  NaN    aodihf     8.0      NaN    NaN

In [87]:
u=employees4.append(employees3)

C:\Users\mahen\AppData\Local\Temp\ipykernel_28084\2973134297.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  u=employees4.append(employees3)


In [88]:
ab=pd.concat([employees4,employees3])

In [89]:
ab

id      name  mgr_id   salary    age
0  1.0  mahendra     2.0  40000.0  120.0
1  2.0      mahi     3.0  30000.0  160.0
2  5.0      maha     NaN  20000.0   80.0
3  3.0       sam     5.0  50000.0  180.0
4  NaN    aodihf     8.0      NaN    NaN
0  1.0  mahendra     2.0  40000.0  120.0
1  2.0      mahi     3.0  30000.0  160.0
2  5.0      maha     NaN  20000.0   80.0
3  3.0       sam     5.0  50000.0  180.0
4  NaN    aodihf     8.0      NaN    NaN

In [90]:
ab.drop('abc',axis=1, inplace=True)

KeyError: "['abc'] not found in axis"

In [91]:
ab

id      name  mgr_id   salary    age
0  1.0  mahendra     2.0  40000.0  120.0
1  2.0      mahi     3.0  30000.0  160.0
2  5.0      maha     NaN  20000.0   80.0
3  3.0       sam     5.0  50000.0  180.0
4  NaN    aodihf     8.0      NaN    NaN
0  1.0  mahendra     2.0  40000.0  120.0
1  2.0      mahi     3.0  30000.0  160.0
2  5.0      maha     NaN  20000.0   80.0
3  3.0       sam     5.0  50000.0  180.0
4  NaN    aodihf     8.0      NaN    NaN

In [92]:
ab.drop_duplicates(inplace=True)

In [93]:
ab

id      name  mgr_id   salary    age
0  1.0  mahendra     2.0  40000.0  120.0
1  2.0      mahi     3.0  30000.0  160.0
2  5.0      maha     NaN  20000.0   80.0
3  3.0       sam     5.0  50000.0  180.0
4  NaN    aodihf     8.0      NaN    NaN

In [94]:
op=u.drop_duplicates(inplace=True)

In [95]:
op

In [96]:
empl=employees3.merge(employees3, left_on = 'mgr_id', right_on ='id', how='inner', suffixes =['', '_managers'] )
empl

id      name  mgr_id   salary    age  id_managers name_managers  \
0  1.0  mahendra     2.0  40000.0  120.0          2.0          mahi   
1  2.0      mahi     3.0  30000.0  160.0          3.0           sam   
2  5.0      maha     NaN  20000.0   80.0          NaN        aodihf   
3  3.0       sam     5.0  50000.0  180.0          5.0          maha   

   mgr_id_managers  salary_managers  age_managers  
0              3.0          30000.0         160.0  
1              5.0          50000.0         180.0  
2              8.0              NaN           NaN  
3              NaN          20000.0          80.0

In [97]:
empl1=empl[['id', 'name','salary','salary_managers']]
empl1

id      name   salary  salary_managers
0  1.0  mahendra  40000.0          30000.0
1  2.0      mahi  30000.0          50000.0
2  5.0      maha  20000.0              NaN
3  3.0       sam  50000.0          20000.0

In [98]:
empl1.sort_values(by='salary')

id      name   salary  salary_managers
2  5.0      maha  20000.0              NaN
1  2.0      mahi  30000.0          50000.0
0  1.0  mahendra  40000.0          30000.0
3  3.0       sam  50000.0          20000.0

In [99]:
empl1.sort_values(by='name',ascending = True)

id      name   salary  salary_managers
2  5.0      maha  20000.0              NaN
0  1.0  mahendra  40000.0          30000.0
1  2.0      mahi  30000.0          50000.0
3  3.0       sam  50000.0          20000.0

In [100]:
empl1[empl1['salary']>empl1['salary_managers']]

id      name   salary  salary_managers
0  1.0  mahendra  40000.0          30000.0
3  3.0       sam  50000.0          20000.0

In [101]:
empl[empl1['salary']>empl1['salary_managers']]

id      name  mgr_id   salary    age  id_managers name_managers  \
0  1.0  mahendra     2.0  40000.0  120.0          2.0          mahi   
3  3.0       sam     5.0  50000.0  180.0          5.0          maha   

   mgr_id_managers  salary_managers  age_managers  
0              3.0          30000.0         160.0  
3              NaN          20000.0          80.0

In [102]:
empl['salary']<empl['salary_managers']

0    False
1     True
2    False
3    False
dtype: bool

In [103]:
empl[empl['salary']<empl['salary_managers']]

id  name  mgr_id   salary    age  id_managers name_managers  \
1  2.0  mahi     3.0  30000.0  160.0          3.0           sam   

   mgr_id_managers  salary_managers  age_managers  
1              5.0          50000.0         180.0

In [104]:
empl=employees3.merge(employees3, left_on = 'mgr_id', right_on ='id', how='left', suffixes =['', '_managers'] )

In [105]:
empl

id      name  mgr_id   salary    age  id_managers name_managers  \
0  1.0  mahendra     2.0  40000.0  120.0          2.0          mahi   
1  2.0      mahi     3.0  30000.0  160.0          3.0           sam   
2  5.0      maha     NaN  20000.0   80.0          NaN        aodihf   
3  3.0       sam     5.0  50000.0  180.0          5.0          maha   
4  NaN    aodihf     8.0      NaN    NaN          NaN           NaN   

   mgr_id_managers  salary_managers  age_managers  
0              3.0          30000.0         160.0  
1              5.0          50000.0         180.0  
2              8.0              NaN           NaN  
3              NaN          20000.0          80.0  
4              NaN              NaN           NaN

In [106]:
empl=employees3.merge(employees3, left_on = 'mgr_id', right_on ='id', how='right', suffixes =['_emp', '_mgr'] )

In [107]:
empl

id_emp  name_emp  mgr_id_emp  salary_emp  age_emp  id_mgr  name_mgr  \
0     NaN       NaN         NaN         NaN      NaN     1.0  mahendra   
1     1.0  mahendra         2.0     40000.0    120.0     2.0      mahi   
2     3.0       sam         5.0     50000.0    180.0     5.0      maha   
3     2.0      mahi         3.0     30000.0    160.0     3.0       sam   
4     5.0      maha         NaN     20000.0     80.0     NaN    aodihf   

   mgr_id_mgr  salary_mgr  age_mgr  
0         2.0     40000.0    120.0  
1         3.0     30000.0    160.0  
2         NaN     20000.0     80.0  
3         5.0     50000.0    180.0  
4         8.0         NaN      NaN

In [108]:
empl=employees3.merge(employees3, left_on = 'mgr_id', right_on ='id', how='outer', suffixes =['_emp', '_mgr'] )

In [109]:
empl

id_emp  name_emp  mgr_id_emp  salary_emp  age_emp  id_mgr  name_mgr  \
0     1.0  mahendra         2.0     40000.0    120.0     2.0      mahi   
1     2.0      mahi         3.0     30000.0    160.0     3.0       sam   
2     5.0      maha         NaN     20000.0     80.0     NaN    aodihf   
3     3.0       sam         5.0     50000.0    180.0     5.0      maha   
4     NaN    aodihf         8.0         NaN      NaN     NaN       NaN   
5     NaN       NaN         NaN         NaN      NaN     1.0  mahendra   

   mgr_id_mgr  salary_mgr  age_mgr  
0         3.0     30000.0    160.0  
1         5.0     50000.0    180.0  
2         8.0         NaN      NaN  
3         NaN     20000.0     80.0  
4         NaN         NaN      NaN  
5         2.0     40000.0    120.0

In [110]:
employees4

id      name  mgr_id   salary    age
0  1.0  mahendra     2.0  40000.0  120.0
1  2.0      mahi     3.0  30000.0  160.0
2  5.0      maha     NaN  20000.0   80.0
3  3.0       sam     5.0  50000.0  180.0
4  NaN    aodihf     8.0      NaN    NaN

In [111]:
def departments_add(y):
    if y['salary']> 40000:
        return 'development'
    elif y['salary']<=20000:
        return 'Data'
    else:
        return 'support'

In [112]:
employees3

id      name  mgr_id   salary    age
0  1.0  mahendra     2.0  40000.0  120.0
1  2.0      mahi     3.0  30000.0  160.0
2  5.0      maha     NaN  20000.0   80.0
3  3.0       sam     5.0  50000.0  180.0
4  NaN    aodihf     8.0      NaN    NaN

In [113]:
a=employees3.apply(departments_add, axis=1)

In [114]:
a

0        support
1        support
2           Data
3    development
4        support
dtype: object

In [115]:
employees3['department']=a

In [116]:
employees3

id      name  mgr_id   salary    age   department
0  1.0  mahendra     2.0  40000.0  120.0      support
1  2.0      mahi     3.0  30000.0  160.0      support
2  5.0      maha     NaN  20000.0   80.0         Data
3  3.0       sam     5.0  50000.0  180.0  development
4  NaN    aodihf     8.0      NaN    NaN      support

In [117]:
employees3

id      name  mgr_id   salary    age   department
0  1.0  mahendra     2.0  40000.0  120.0      support
1  2.0      mahi     3.0  30000.0  160.0      support
2  5.0      maha     NaN  20000.0   80.0         Data
3  3.0       sam     5.0  50000.0  180.0  development
4  NaN    aodihf     8.0      NaN    NaN      support

In [118]:
employees3.drop('abc', axis=1, inplace=True)

KeyError: "['abc'] not found in axis"

In [119]:
#select department, sum(salary) from table group by department -----department wise total salary

total_salary = employees3.groupby('department')['salary', 'id'].sum().reset_index(name=['total_salary_department_wise','total_id'])

C:\Users\mahen\AppData\Local\Temp\ipykernel_28084\1545165001.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  total_salary = employees3.groupby('department')['salary', 'id'].sum().reset_index(name=['total_salary_department_wise','total_id'])


TypeError: DataFrame.reset_index() got an unexpected keyword argument 'name'

In [120]:
total_salary = employees3.groupby('department').agg(
    total_salary_department_wise=('salary', 'sum'),
    number_of_employees=('id', 'count'), 
    min_salary=('salary', 'min'), 
    max_salary=('salary', 'max')
).reset_index()

In [121]:
total_salary

department  total_salary_department_wise  number_of_employees  min_salary  \
0         Data                       20000.0                    1     20000.0   
1  development                       50000.0                    1     50000.0   
2      support                       70000.0                    2     30000.0   

   max_salary  
0     20000.0  
1     50000.0  
2     40000.0

In [122]:
total_salary.sort_values(by='total_salary_department_wise', ascending = False)

department  total_salary_department_wise  number_of_employees  min_salary  \
2      support                       70000.0                    2     30000.0   
1  development                       50000.0                    1     50000.0   
0         Data                       20000.0                    1     20000.0   

   max_salary  
2     40000.0  
1     50000.0  
0     20000.0

In [123]:
total_salary

department  total_salary_department_wise  number_of_employees  min_salary  \
0         Data                       20000.0                    1     20000.0   
1  development                       50000.0                    1     50000.0   
2      support                       70000.0                    2     30000.0   

   max_salary  
0     20000.0  
1     50000.0  
2     40000.0

In [124]:
number_of_employees = employees3.groupby(['department'])['name', 'id'].count()

C:\Users\mahen\AppData\Local\Temp\ipykernel_28084\1447812946.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  number_of_employees = employees3.groupby(['department'])['name', 'id'].count()


In [125]:
number_of_employees

name  id
department           
Data            1   1
development     1   1
support         3   2

In [126]:
employees3

id      name  mgr_id   salary    age   department
0  1.0  mahendra     2.0  40000.0  120.0      support
1  2.0      mahi     3.0  30000.0  160.0      support
2  5.0      maha     NaN  20000.0   80.0         Data
3  3.0       sam     5.0  50000.0  180.0  development
4  NaN    aodihf     8.0      NaN    NaN      support

In [128]:
data =pd.read_excel("Health_Sleep_Statistics.xlsx")

In [129]:
data

User ID  Age Gender  Sleep Quality   Bedtime Wake-up Time  Daily Steps  \
0         1   25      f              8  23:00:00     06:30:00         8000   
1         2   34      m              7  00:30:00     07:00:00         5000   
2         3   29      f              9  22:45:00     06:45:00         9000   
3         4   41      m              5  01:00:00     06:30:00         4000   
4         5   22      f              8  23:30:00     07:00:00        10000   
..      ...  ...    ...            ...       ...          ...          ...   
95       96   43      m              7  00:45:00     07:15:00         6500   
96       97   33      f              8  23:15:00     06:15:00         8500   
97       98   46      m              4  01:30:00     07:00:00         3000   
98       99   25      f              9  22:15:00     06:45:00         9500   
99      100   41      m              6  00:30:00     07:00:00         5000   

    Calories Burned Physical Activity Level Dietary Habits Sleep Disorders  \
0              2500                  medium        healthy              no   
1              2200                     low      unhealthy             yes   
2              2700                    high        healthy              no   
3              2100                     low      unhealthy             yes   
4              2800                    high         medium              no   
..              ...                     ...            ...             ...   
95             2400                  medium         medium              no   
96             2600                    high         medium              no   
97             2000                     low      unhealthy             yes   
98             2700                    high        healthy              no   
99             2200                  medium      unhealthy              no   

   Medication Usage  
0                no  
1               yes  
2                no  
3                no  
4                no  
..              ...  
95               no  
96               no  
97              yes  
98               no  
99               no  

[100 rows x 12 columns]

In [131]:
health_data=pd.read_excel("Health_Sleep_Statistics.xlsx")

In [132]:
health_data

User ID  Age Gender  Sleep Quality   Bedtime Wake-up Time  Daily Steps  \
0         1   25      f              8  23:00:00     06:30:00         8000   
1         2   34      m              7  00:30:00     07:00:00         5000   
2         3   29      f              9  22:45:00     06:45:00         9000   
3         4   41      m              5  01:00:00     06:30:00         4000   
4         5   22      f              8  23:30:00     07:00:00        10000   
..      ...  ...    ...            ...       ...          ...          ...   
95       96   43      m              7  00:45:00     07:15:00         6500   
96       97   33      f              8  23:15:00     06:15:00         8500   
97       98   46      m              4  01:30:00     07:00:00         3000   
98       99   25      f              9  22:15:00     06:45:00         9500   
99      100   41      m              6  00:30:00     07:00:00         5000   

    Calories Burned Physical Activity Level Dietary Habits Sleep Disorders  \
0              2500                  medium        healthy              no   
1              2200                     low      unhealthy             yes   
2              2700                    high        healthy              no   
3              2100                     low      unhealthy             yes   
4              2800                    high         medium              no   
..              ...                     ...            ...             ...   
95             2400                  medium         medium              no   
96             2600                    high         medium              no   
97             2000                     low      unhealthy             yes   
98             2700                    high        healthy              no   
99             2200                  medium      unhealthy              no   

   Medication Usage  
0                no  
1               yes  
2                no  
3                no  
4                no  
..              ...  
95               no  
96               no  
97              yes  
98               no  
99               no  

[100 rows x 12 columns]

In [136]:
health_data1=pd.read_csv("Health_Sleep_Statistics.csv")

In [137]:
health_data1

User ID  Age Gender  Sleep Quality Bedtime Wake-up Time  Daily Steps  \
0         1   25      f              8   23:00        06:30         8000   
1         2   34      m              7   00:30        07:00         5000   
2         3   29      f              9   22:45        06:45         9000   
3         4   41      m              5   01:00        06:30         4000   
4         5   22      f              8   23:30        07:00        10000   
..      ...  ...    ...            ...     ...          ...          ...   
95       96   43      m              7   00:45        07:15         6500   
96       97   33      f              8   23:15        06:15         8500   
97       98   46      m              4   01:30        07:00         3000   
98       99   25      f              9   22:15        06:45         9500   
99      100   41      m              6   00:30        07:00         5000   

    Calories Burned Physical Activity Level Dietary Habits Sleep Disorders  \
0              2500                  medium        healthy              no   
1              2200                     low      unhealthy             yes   
2              2700                    high        healthy              no   
3              2100                     low      unhealthy             yes   
4              2800                    high         medium              no   
..              ...                     ...            ...             ...   
95             2400                  medium         medium              no   
96             2600                    high         medium              no   
97             2000                     low      unhealthy             yes   
98             2700                    high        healthy              no   
99             2200                  medium      unhealthy              no   

   Medication Usage  
0                no  
1               yes  
2                no  
3                no  
4                no  
..              ...  
95               no  
96               no  
97              yes  
98               no  
99               no  

[100 rows x 12 columns]

In [138]:
health1=pd.read_csv("Health_Sleep_Statistics.csv")

In [139]:
health1

User ID  Age Gender  Sleep Quality Bedtime Wake-up Time  Daily Steps  \
0         1   25      f              8   23:00        06:30         8000   
1         2   34      m              7   00:30        07:00         5000   
2         3   29      f              9   22:45        06:45         9000   
3         4   41      m              5   01:00        06:30         4000   
4         5   22      f              8   23:30        07:00        10000   
..      ...  ...    ...            ...     ...          ...          ...   
95       96   43      m              7   00:45        07:15         6500   
96       97   33      f              8   23:15        06:15         8500   
97       98   46      m              4   01:30        07:00         3000   
98       99   25      f              9   22:15        06:45         9500   
99      100   41      m              6   00:30        07:00         5000   

    Calories Burned Physical Activity Level Dietary Habits Sleep Disorders  \
0              2500                  medium        healthy              no   
1              2200                     low      unhealthy             yes   
2              2700                    high        healthy              no   
3              2100                     low      unhealthy             yes   
4              2800                    high         medium              no   
..              ...                     ...            ...             ...   
95             2400                  medium         medium              no   
96             2600                    high         medium              no   
97             2000                     low      unhealthy             yes   
98             2700                    high        healthy              no   
99             2200                  medium      unhealthy              no   

   Medication Usage  
0                no  
1               yes  
2                no  
3                no  
4                no  
..              ...  
95               no  
96               no  
97              yes  
98               no  
99               no  

[100 rows x 12 columns]

In [140]:
health2=pd.read_excel("Health_Sleep_Statistics.xlsx")

In [141]:
health2

User ID  Age Gender  Sleep Quality   Bedtime Wake-up Time  Daily Steps  \
0         1   25      f              8  23:00:00     06:30:00         8000   
1         2   34      m              7  00:30:00     07:00:00         5000   
2         3   29      f              9  22:45:00     06:45:00         9000   
3         4   41      m              5  01:00:00     06:30:00         4000   
4         5   22      f              8  23:30:00     07:00:00        10000   
..      ...  ...    ...            ...       ...          ...          ...   
95       96   43      m              7  00:45:00     07:15:00         6500   
96       97   33      f              8  23:15:00     06:15:00         8500   
97       98   46      m              4  01:30:00     07:00:00         3000   
98       99   25      f              9  22:15:00     06:45:00         9500   
99      100   41      m              6  00:30:00     07:00:00         5000   

    Calories Burned Physical Activity Level Dietary Habits Sleep Disorders  \
0              2500                  medium        healthy              no   
1              2200                     low      unhealthy             yes   
2              2700                    high        healthy              no   
3              2100                     low      unhealthy             yes   
4              2800                    high         medium              no   
..              ...                     ...            ...             ...   
95             2400                  medium         medium              no   
96             2600                    high         medium              no   
97             2000                     low      unhealthy             yes   
98             2700                    high        healthy              no   
99             2200                  medium      unhealthy              no   

   Medication Usage  
0                no  
1               yes  
2                no  
3                no  
4                no  
..              ...  
95               no  
96               no  
97              yes  
98               no  
99               no  

[100 rows x 12 columns]

In [142]:
health2.tail(10)

User ID  Age Gender  Sleep Quality   Bedtime Wake-up Time  Daily Steps  \
90       91   23      f              9  22:15:00     06:45:00         9500   
91       92   36      m              6  00:30:00     07:00:00         5000   
92       93   29      f              8  23:00:00     07:00:00         8500   
93       94   50      m              5  01:15:00     07:00:00         4000   
94       95   27      f              9  22:30:00     07:30:00         9000   
95       96   43      m              7  00:45:00     07:15:00         6500   
96       97   33      f              8  23:15:00     06:15:00         8500   
97       98   46      m              4  01:30:00     07:00:00         3000   
98       99   25      f              9  22:15:00     06:45:00         9500   
99      100   41      m              6  00:30:00     07:00:00         5000   

    Calories Burned Physical Activity Level Dietary Habits Sleep Disorders  \
90             2700                    high        healthy              no   
91             2200                  medium      unhealthy              no   
92             2600                  medium         medium              no   
93             2100                     low      unhealthy             yes   
94             2750                    high        healthy              no   
95             2400                  medium         medium              no   
96             2600                    high         medium              no   
97             2000                     low      unhealthy             yes   
98             2700                    high        healthy              no   
99             2200                  medium      unhealthy              no   

   Medication Usage  
90               no  
91               no  
92               no  
93               no  
94               no  
95               no  
96               no  
97              yes  
98               no  
99               no

In [143]:
health2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   User ID                  100 non-null    int64 
 1   Age                      100 non-null    int64 
 2   Gender                   100 non-null    object
 3   Sleep Quality            100 non-null    int64 
 4   Bedtime                  100 non-null    object
 5   Wake-up Time             100 non-null    object
 6   Daily Steps              100 non-null    int64 
 7   Calories Burned          100 non-null    int64 
 8   Physical Activity Level  100 non-null    object
 9   Dietary Habits           100 non-null    object
 10  Sleep Disorders          100 non-null    object
 11  Medication Usage         100 non-null    object
dtypes: int64(5), object(7)
memory usage: 9.5+ KB


In [144]:
health2.describe()

User ID         Age  Sleep Quality   Daily Steps  Calories Burned
count  100.000000  100.000000     100.000000    100.000000        100.00000
mean    50.500000   36.010000       7.000000   6830.000000       2421.00000
std     29.011492    8.454865       1.734964   2498.706736        281.06759
min      1.000000   22.000000       4.000000   3000.000000       2000.00000
25%     25.750000   28.750000       5.750000   4750.000000       2175.00000
50%     50.500000   35.000000       7.500000   6750.000000       2400.00000
75%     75.250000   44.000000       8.250000   9000.000000       2700.00000
max    100.000000   50.000000       9.000000  11000.000000       2900.00000

In [145]:
health2.count()

User ID                    100
Age                        100
Gender                     100
Sleep Quality              100
Bedtime                    100
Wake-up Time               100
Daily Steps                100
Calories Burned            100
Physical Activity Level    100
Dietary Habits             100
Sleep Disorders            100
Medication Usage           100
dtype: int64

In [146]:
health2['User ID'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100], dtype=int64)

In [147]:
health2['User ID'].nunique()

100

In [148]:
health2['Age'].nunique()

29

In [149]:
health2['Age'].unique()

array([25, 34, 29, 41, 22, 37, 30, 45, 27, 32, 50, 23, 36, 48, 28, 31, 26,
       39, 33, 42, 35, 40, 47, 44, 38, 49, 24, 46, 43], dtype=int64)

In [150]:
health2['Gender'].unique()

array(['f', 'm'], dtype=object)

In [151]:
health2['Gender'].nunique()

2

In [152]:
health3=health2.copy()

In [153]:
health3

User ID  Age Gender  Sleep Quality   Bedtime Wake-up Time  Daily Steps  \
0         1   25      f              8  23:00:00     06:30:00         8000   
1         2   34      m              7  00:30:00     07:00:00         5000   
2         3   29      f              9  22:45:00     06:45:00         9000   
3         4   41      m              5  01:00:00     06:30:00         4000   
4         5   22      f              8  23:30:00     07:00:00        10000   
..      ...  ...    ...            ...       ...          ...          ...   
95       96   43      m              7  00:45:00     07:15:00         6500   
96       97   33      f              8  23:15:00     06:15:00         8500   
97       98   46      m              4  01:30:00     07:00:00         3000   
98       99   25      f              9  22:15:00     06:45:00         9500   
99      100   41      m              6  00:30:00     07:00:00         5000   

    Calories Burned Physical Activity Level Dietary Habits Sleep Disorders  \
0              2500                  medium        healthy              no   
1              2200                     low      unhealthy             yes   
2              2700                    high        healthy              no   
3              2100                     low      unhealthy             yes   
4              2800                    high         medium              no   
..              ...                     ...            ...             ...   
95             2400                  medium         medium              no   
96             2600                    high         medium              no   
97             2000                     low      unhealthy             yes   
98             2700                    high        healthy              no   
99             2200                  medium      unhealthy              no   

   Medication Usage  
0                no  
1               yes  
2                no  
3                no  
4                no  
..              ...  
95               no  
96               no  
97              yes  
98               no  
99               no  

[100 rows x 12 columns]

In [154]:
health3.describe()

User ID         Age  Sleep Quality   Daily Steps  Calories Burned
count  100.000000  100.000000     100.000000    100.000000        100.00000
mean    50.500000   36.010000       7.000000   6830.000000       2421.00000
std     29.011492    8.454865       1.734964   2498.706736        281.06759
min      1.000000   22.000000       4.000000   3000.000000       2000.00000
25%     25.750000   28.750000       5.750000   4750.000000       2175.00000
50%     50.500000   35.000000       7.500000   6750.000000       2400.00000
75%     75.250000   44.000000       8.250000   9000.000000       2700.00000
max    100.000000   50.000000       9.000000  11000.000000       2900.00000

In [155]:
health3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   User ID                  100 non-null    int64 
 1   Age                      100 non-null    int64 
 2   Gender                   100 non-null    object
 3   Sleep Quality            100 non-null    int64 
 4   Bedtime                  100 non-null    object
 5   Wake-up Time             100 non-null    object
 6   Daily Steps              100 non-null    int64 
 7   Calories Burned          100 non-null    int64 
 8   Physical Activity Level  100 non-null    object
 9   Dietary Habits           100 non-null    object
 10  Sleep Disorders          100 non-null    object
 11  Medication Usage         100 non-null    object
dtypes: int64(5), object(7)
memory usage: 9.5+ KB


In [156]:
health3['Age']=health3['Age'].astype('str')

In [157]:
health3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   User ID                  100 non-null    int64 
 1   Age                      100 non-null    object
 2   Gender                   100 non-null    object
 3   Sleep Quality            100 non-null    int64 
 4   Bedtime                  100 non-null    object
 5   Wake-up Time             100 non-null    object
 6   Daily Steps              100 non-null    int64 
 7   Calories Burned          100 non-null    int64 
 8   Physical Activity Level  100 non-null    object
 9   Dietary Habits           100 non-null    object
 10  Sleep Disorders          100 non-null    object
 11  Medication Usage         100 non-null    object
dtypes: int64(4), object(8)
memory usage: 9.5+ KB


In [ ]:

for col in health3.select_dtypes(include=['object']).columns:
    health3[col] = pd.to_numeric(df['Age'], errors='coerce').astype('str')

print(df.dtypes)
print(df)
